version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: mysqldb
      DATABASE_PORT: 3306
      DATABASE_NAME: bcc_forum
      DATABASE_USER: root
      DATABASE_PASSWORD: "root"
    ports:
      - "8500:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: bcc_forum
      MYSQL_USER: root
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: